"""Stage 5: Crystallizer —— 走 M1.5 结晶(已有模块接)。

**AC8 不变量**:产出**可**被 Paradigm Loader 加载的 SKILL.md。

本拍**简**化版:把 Implementation 整合成 SKILL.md frontmatter 格式(M2+ 真调
M1.5 crystallize 模块,本拍只走协议层)。

设计:docs/12 §3.1 Stage 5。
"""

from __future__ import annotations

import dataclasses
import pathlib
from typing import Optional

from .implement import Implementation


# agentskills.io 标准 frontmatter 必含字段(M1.5 已对齐)
SKILL_FRONTMATTER_FIELDS: tuple[str, ...] = (
    "name",
    "description",
)


@dataclasses.dataclass(frozen=True)
class SkillCandidate:
    """Stage 5 产出的 SKILL.md 候选。"""
    skill_md_text: str
    skill_path: pathlib.Path
    name: str

    def has_agentskills_io_frontmatter(self) -> bool:
        """AC8 校验:含 agentskills.io 必填字段 name + description。"""
        return all(
            f"{f}:" in self.skill_md_text
            for f in SKILL_FRONTMATTER_FIELDS
        )


def crystallize(
    impl: Implementation,
    spec_goal: str,
    *,
    base_dir: Optional[pathlib.Path] = None,
) -> SkillCandidate:
    """把 Implementation 整合成 SKILL.md(走 agentskills.io 标准 frontmatter)。

    AC8 验证:返回的 SkillCandidate.has_agentsskills_io_frontmatter() = True
    """
    if base_dir is None:
        import tempfile
        base_dir = pathlib.Path(tempfile.gettempdir()) / "karvyloop_spec_coding" / "skills"
    base_dir.mkdir(parents=True, exist_ok=True)
    # name 化:用 spec_goal 的前 30 字符 + 替换空格为 _
    name = "auto_" + spec_goal[:30].replace(" ", "_").replace("/", "_")
    skill_path = base_dir / f"{name}.md"
    skill_md = (
        f"---\n"
        f"name: {name}\n"
        f"description: Auto-generated skill for: {spec_goal}\n"
        f"---\n"
        f"\n"
        f"# {name}\n"
        f"\n"
        f"Auto-generated by karvyloop.spec_coding (M2.0 拍 2).\n"
        f"\n"
        f"## 实现\n\n"
        f"```python\n"
        f"{impl.code}\n"
        f"```\n"
        f"\n"
        f"## Tech used\n\n"
        f"{', '.join(impl.used_tech.atoms) or '(no atoms)'}\n"
    )
    skill_path.write_text(skill_md, encoding="utf-8")
    return SkillCandidate(skill_md_text=skill_md, skill_path=skill_path, name=name)
