"""Stage 4: Implementer —— spec + tech → 实现。

**AC4 不变量**:实现**不**写到主目录(走 sandbox / tmp)。

本拍**简**化版:把 spec.md + tech 整合成实现草稿(纯文本,**不**真调 Forge——
真调 Forge 留给 M2+ 升级,本拍只走协议层)。

设计:docs/12 §3.1 Stage 4。
"""

from __future__ import annotations

import dataclasses
import pathlib
from typing import Optional

from .spec import Spec
from .tech_select import TechStack


@dataclasses.dataclass(frozen=True)
class Implementation:
    """Stage 4 产出的实现(简化版:代码草稿 + 写到哪)。"""
    code: str               # 实现草稿(M2+ 调 Forge 真写)
    artifact_path: pathlib.Path  # 写到 sandbox / tmp 的路径(AC4:不**写**主目录)
    used_tech: TechStack

    def exists(self) -> bool:
        return self.artifact_path.exists()


def implement(
    spec: Spec,
    tech: TechStack,
    *,
    base_dir: Optional[pathlib.Path] = None,
) -> Implementation:
    """简化版实现:把 spec + tech 整合成 Python 函数草稿,写到 sandbox。

    AC4:写到的目录 = base_dir(测试可注入,默认 = tmp 目录)
    AC3:用到的 tech.is_valid() 必须 True
    """
    # 默认写到 tmpdir(生产环境由 Forge 接 sandbox;本拍实现协议层)
    if base_dir is None:
        import tempfile
        base_dir = pathlib.Path(tempfile.gettempdir()) / "karvyloop_spec_coding"
    base_dir.mkdir(parents=True, exist_ok=True)
    artifact = base_dir / f"impl_{spec.goal[:20].replace(' ', '_')}.py"
    # 代码草稿:用 tech.atoms 调用的 Python 骨架
    atom_calls = "\n    ".join(
        f"result = await atom_registry.call({a!r}, input)"
        for a in tech.atoms
    )
    code = (
        f'"""\n'
        f'Auto-generated implementation for: {spec.goal}\n'
        f'Generated by karvyloop.spec_coding\n'
        f'"""\n'
        f'\n'
        f'async def run(input):\n'
        f'    {atom_calls or "pass  # no atoms selected"}\n'
        f'    return result\n'
    )
    artifact.write_text(code, encoding="utf-8")
    return Implementation(code=code, artifact_path=artifact, used_tech=tech)
